UPDATE BRIDGE SET status='ready' FROM BRIDGE b WHERE status='AVAILABLE';
UPDATE BRIDGE SET status='accepted' FROM BRIDGE b WHERE status='REQUESTED';
UPDATE BRIDGE SET status='deprovision' FROM BRIDGE b WHERE status='DELETION_REQUESTED';

UPDATE PROCESSOR SET status='ready' FROM PROCESSOR p WHERE status='AVAILABLE';
UPDATE PROCESSOR SET status='accepted' FROM PROCESSOR p WHERE status='REQUESTED';
UPDATE PROCESSOR SET status='deprovision' FROM PROCESSOR p WHERE status='DELETION_REQUESTED';