UPDATE BRIDGE SET status='READY' FROM BRIDGE b WHERE status='AVAILABLE';
UPDATE BRIDGE SET status='ACCEPTED' FROM BRIDGE b WHERE status='REQUESTED';
UPDATE BRIDGE SET status='DEPROVISION' FROM BRIDGE b WHERE status='DELETION_REQUESTED';

UPDATE PROCESSOR SET status='READY' FROM PROCESSOR p WHERE status='AVAILABLE';
UPDATE PROCESSOR SET status='ACCEPTED' FROM PROCESSOR p WHERE status='REQUESTED';
UPDATE PROCESSOR SET status='DEPROVISION' FROM PROCESSOR p WHERE status='DELETION_REQUESTED';