{
 "title": "Processing Errors Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Poll requests for errors over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{method=\"GET\",outcome=\"SUCCESS\",uri=\"/api/smartevents_mgmt/v1/bridges/{bridgeId}/errors\",}[1m])"
    }
   ]
  },
  {
   "title": "Failed poll requests for errors over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{method=\"GET\",outcome!=\"SUCCESS\",uri=\"/api/smartevents_mgmt/v1/bridges/{bridgeId}/errors\",}[1m])"
    }
   ]
  },
  {
   "title": "Unsuccessful bridge creation rate over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{method=\"GET\",outcome!=\"SUCCESS\",uri=\"/api/smartevents_mgmt/v1/bridges/{bridgeId}/errors\",}[1m]))/sum(increase(http_server_requests_seconds_count{method=\"GET\",uri=\"/api/smartevents_mgmt/v1/bridges/{bridgeId}/errors\",}[1m]))"
    }
   ]
  },
  {
   "title": "Messages in error topic over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kafka_consumer_fetch_manager_records_consumed_total{topic!=\"\"}[1m])"
    }
   ]
  }
 ]
}