{
 "title": "Executor Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Processor with the maximum 1m average processing time for filters",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(increase(executor_filter_evaluation_seconds_sum[1m])/increase(executor_filter_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Processor with the maximum 1m average processing time for transformation",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "max(increase(executor_transformation_evaluation_seconds_sum[1m])/increase(executor_transformation_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Processor with the maximum 1m average processing time for actions",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "max(increase(executor_action_evaluation_seconds_sum[1m])/increase(executor_action_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Number of filters processed every 1 minutes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(executor_filter_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Number of transformations processed every 1 minutes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(executor_transformation_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Number of actions processed every 1 minutes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(executor_action_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Top 5 processors with 1m average time for filters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(executor_filter_evaluation_seconds_sum[1m])/increase(executor_filter_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Top 5 processors with 1m average time for transformations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(executor_transformation_evaluation_seconds_sum[1m])/increase(executor_transformation_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Top 5 processors with 1m average time for actions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(executor_filter_evaluation_seconds_sum[1m])/increase(executor_filter_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Global 1m Average processing time for Filters with thresholds",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(executor_action_evaluation_seconds_sum[1m]))/sum(increase(executor_action_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Global 1m Average processing time for Transformations with thresholds",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(executor_transformation_evaluation_seconds_sum[1m]))/sum(increase(executor_transformation_evaluation_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Global 1m Average processing time for Actions with thresholds",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(executor_action_evaluation_seconds_sum[1m]))/sum(increase(executor_action_evaluation_seconds_count[1m]))"
    }
   ]
  }
 ]
}