{
 "title": "Fleet Manager Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Unsuccessful Bridges creation rate over 1 minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{method=\"POST\",status!=\"201\",uri=\"/api/v1/bridges\",}[1m]))/sum(increase(http_server_requests_seconds_count{method=\"POST\",uri=\"/api/v1/bridges\",}[1m]))"
    }
   ]
  },
  {
   "title": "Unsuccessful Processor creation rate over 1 minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{method=\"POST\",status!=\"201\",uri=\"/api/v1/bridges/{bridgeId}/processors\",}[1m]))/sum(increase(http_server_requests_seconds_count{method=\"POST\",uri=\"/api/v1/bridges/{bridgeId}/processors\",}[1m]))"
    }
   ]
  },
  {
   "title": "Unsuccessful bridge creation rate over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{method=\"POST\",status!=\"201\",uri=\"/api/v1/bridges\",}[1m]))/sum(increase(http_server_requests_seconds_count{method=\"POST\",uri=\"/api/v1/bridges\",}[1m]))"
    }
   ]
  },
  {
   "title": "Unsuccessful processor creation rate over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{method=\"POST\",status!=\"201\",uri=\"/api/v1/bridges/{bridgeId}/processors\",}[1m]))/sum(increase(http_server_requests_seconds_count{method=\"POST\",uri=\"/api/v1/bridges/{bridgeId}/processors\",}[1m]))"
    }
   ]
  },
  {
   "title": "Number of Bridges created successfully over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{method=\"POST\",outcome=\"SUCCESS\",status=\"201\",uri=\"/api/v1/bridges\",}[1m])"
    }
   ]
  },
  {
   "title": "Number of Processors created successfully over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{method=\"POST\",outcome=\"SUCCESS\",status=\"201\",uri=\"/api/v1/bridges/{bridgeId}/processors\",}[1m])"
    }
   ]
  },
  {
   "title": "Number of unsuccessfull bridges creation requests over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{method=\"POST\",status!=\"201\",uri=\"/api/v1/bridges\",}[1m]))"
    }
   ]
  },
  {
   "title": "Number of unsuccessfull processor creation requests over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{method=\"POST\",status!=\"201\",uri=\"/api/v1/bridges/{bridgeId}/processors\",}[1m]))"
    }
   ]
  },
  {
   "title": "Average request processing time for Bridge creation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{method=\"POST\",uri=\"/api/v1/bridges\",}[1m]))/sum(increase(http_server_requests_seconds_count{method=\"POST\",uri=\"/api/v1/bridges\",}[1m]))"
    }
   ]
  },
  {
   "title": "Average request processing time for Processor creation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{method=\"POST\",uri=\"/api/v1/bridges/{bridgeId}/processors\",}[1m]))/sum(increase(http_server_requests_seconds_count{method=\"POST\",uri=\"/api/v1/bridges/{bridgeId}/processors\",}[1m]))"
    }
   ]
  },
  {
   "title": "Bridge status change notification over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(manager_bridge_status_change_total[1m])"
    }
   ]
  },
  {
   "title": "Processor status change notification over 1 minute average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(manager_processor_status_change_total[1m])"
    }
   ]
  }
 ]
}