{
 "title": "RHOSE Fleet Manager SLOs",
 "tags": [ "rhose-fleet-manager" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API Availability",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(haproxy_backend_http_responses_total{route=\"rhose-fleet-manager\",exported_namespace=\"rhose-production\",code!=\"5xx\"}[5m]))/sum(rate(haproxy_backend_http_responses_total{route=\"rhose-fleet-manager\",exported_namespace=\"rhose-production\"}[5m]))) * 100",
     "legendFormat": "rhose-fleet-manager"
    }
   ]
  },
  {
   "title": "SLOs",
   "type": "text",
   "description": "Calculated over the last 28 days\n\n",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "options": {
    "content": "Calculated over the last 28 days"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_inbound_request_duration_bucket{job=\"rhose-fleet-manager-metrics\",namespace=\"rhose-production\",code!~\"5..\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_inbound_request_duration_bucket{job=\"rhose-fleet-manager-metrics\",namespace=\"rhose-production\",code!~\"5..\"}[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "API Availability (95%) ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(haproxy_backend_http_responses_total{route=\"rhose-fleet-manager\",exported_namespace=\"rhose-production\",code!=\"5xx\"}[28d]))/sum(rate(haproxy_backend_http_responses_total{route=\"rhose-fleet-manager\",exported_namespace=\"rhose-production\"}[28d]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "API Latency p99 < 1s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_duration_bucket{job=\"rhose-fleet-manager-metrics\",namespace=\"rhose-production\",le=\"1\",code!~\"5..\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"rhose-fleet-manager-metrics\",namespace=\"rhose-production\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "API Latency p90 < 0.1s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_duration_bucket{job=\"rhose-fleet-manager-metrics\",namespace=\"rhose-production\",le=\"0.1\",code!~\"5..\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"rhose-fleet-manager-metrics\",namespace=\"rhose-production\"}[$__range]))) * 100"
    }
   ]
  }
 ]
}