{
 "title": "RHOSE Kafka",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of incoming bytes per second for the cluster in the last five minutes",
   "type": "graph",
   "description": "This ingress metric represents all the data that producers are sending to topics in the cluster. The Kafka instance type determines the maximum incoming byte rate.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_namespace:haproxy_server_bytes_in_total:rate5m"
    }
   ]
  },
  {
   "title": "Amount of storage left in the brokers",
   "type": "graph",
   "description": "Amount of storage, in bytes, that is currently left in the brokers",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_broker_quota_softlimitbytes - increase(kafka_broker_quota_totalstorageusedbytes[30s])"
    }
   ]
  },
  {
   "title": "Number of outgoing bytes per second for the cluster in the last five minutes",
   "type": "graph",
   "description": "This egress metric represents all the data that consumers are receiving from topics in the cluster. The Kafka instance type determines the maximum outgoing byte rate.",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_namespace:haproxy_server_bytes_out_total:rate5m"
    }
   ]
  },
  {
   "title": "The number of topics we are using",
   "type": "gauge",
   "description": "The number of topics we are using",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_topic:kafka_topic_partitions:count"
    }
   ]
  },
  {
   "title": " The number of partitions remaining that we can create ",
   "type": "gauge",
   "description": " This does not include partitions from internal Kafka topics, such as __consumer_offsets and __transaction_state. The Kafka instance type determines the maximum number of partitions",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "  1500 - kafka_topic:kafka_topic_partitions:sum"
    }
   ]
  },
  {
   "title": "Number of partitions in the cluster that are currently offline",
   "type": "gauge",
   "description": "Offline partitions cannot be used by clients for producing or consuming data. Only the broker that is the current controller in the cluster reports this metric. Any other brokers report 0",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offline_partitions_count)"
    }
   ]
  }
 ]
}