{
 "title": "Smart Events CronJob Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total number of RHOSE CronJobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_cronjob_info{cronjob=~\"rhose-.*\"})"
    }
   ]
  },
  {
   "title": "Number of suspended RHOSE CronJobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_cronjob_spec_suspend{cronjob=~\"rhose-.*\"})"
    }
   ]
  },
  {
   "title": "Number of failed RHOSE CronJobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_status_succeeded{job_name=~\"rhose-.*\"}==0)"
    }
   ]
  },
  {
   "title": "Number of successful RHOSE CronJobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_status_succeeded{job_name=~\"rhose-.*\"}==1)"
    }
   ]
  }
 ]
}